spring:
  application:
    name: UserService
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

